#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff262626
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  1 2 3 4 5 6 7 8 9 10
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             first_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                float
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  34
yabai -m config bottom_padding               60
yabai -m config left_padding                 60
yabai -m config right_padding                60
yabai -m config window_gap                   15

# rules
yabai -m rule --add app=Airmail title="[^Airmail]" manage=off

echo "yabai configuration loaded.."
