#!/usr/bin/env sh

# global settings
yabai -m config external_bar                 off
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.80
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  60
yabai -m config bottom_padding               60
yabai -m config left_padding                 60
yabai -m config right_padding                60
yabai -m config window_gap                   15

# border config
yabai -m config window_border on
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555

# rules
yabai -m rule --add app=Airmail title="[^Airmail]" manage=off
yabai -m rule --add app="IntelliJ IDEA" manage=off
yabai -m rule --add app="IntelliJ IDEA" title=".*~/Documents/Develop.*" manage=on
yabai -m rule --add app="JollysFastVNC" manage=off
yabai -m rule --add app="ISL Light" manage=off
yabai -m rule --add app="XLD" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Colibri" title="Colibri Preferences" manage=off
yabai -m rule --add app="Meta" manage=off
yabai -m rule --add app="Sound Control" manage=off
yabai -m rule --add app="Docker Desktop" manage=off
yabai -m rule --add app="eqMac" manage=off
yabai -m rule --add app="Microsoft Remote Desktop" manage=off
yabai -m rule --add app="SqueezePlay" manage=off

echo "yabai configuration loaded.."
