#!/usr/bin/env sh

launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1

yabai -m signal --add event=dock_did_restart action="sudo /usr/local/bin/yabai --load-sa"
sudo /usr/local/bin/yabai --load-sa

# global settings
yabai -m config external_bar                 all:20:0
yabai -m config menubar_opacity              1.0
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config display_arrangment_order     default
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_zoom_persist          on
yabai -m config window_shadow                on
yabai -m config window_animation_duration    0.0
yabai -m config window_animation_easing      ease_out_circ
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.70
yabai -m config window_opacity               on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap


# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# rules
yabai -m rule --add app=Airmail title="[^Airmail]" manage=off
yabai -m rule --add app="IntelliJ IDEA" manage=off
yabai -m rule --add app="IntelliJ IDEA" title=".*~/Documents/Develop.*" manage=on
yabai -m rule --add app="JollysFastVNC" manage=off
yabai -m rule --add app="ISL Light" manage=off
yabai -m rule --add app="XLD" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Colibri" title="Colibri Preferences" manage=off
yabai -m rule --add app="Meta" manage=off
yabai -m rule --add app="Sound Control" manage=off
yabai -m rule --add app="Docker Desktop" manage=off
yabai -m rule --add app="eqMac" manage=off
#yabai -m rule --add app="Microsoft Remote Desktop" manage=off
yabai -m rule --add app="SqueezePlay" manage=off

echo "yabai configuration loaded.."
